"use client";

import * as React from 'react';
import {
  CERT_HEIGHT,
  CERT_WIDTH,
  DEEP,
  GOLD,
  INK,
  NAVY,
  PAPER,
} from '@/lib/certificates/theme';
import { cormorant, cutive, pinyon } from '@/lib/certificates/fonts';
import { GuillocheBorder } from './ornaments/GuillocheBorder';
import { CornerFleuron } from './ornaments/CornerFleuron';
import { RibbonBanner } from './ornaments/RibbonBanner';
import { SignaturePlaceholder } from './ornaments/SignaturePlaceholder';
import { VerifySeal } from './ornaments/VerifySeal';

// Resolved font-family strings (next/font already includes the autogenerated
// metric-adjusted fallback). Using these directly instead of var(--...) means
// html2canvas can resolve the family from getComputedStyle without depending
// on a parent's CSS custom property — which it doesn't always honor.
const FF_BODY = `${cormorant.style.fontFamily}, Georgia, serif`;
const FF_SCRIPT = `${pinyon.style.fontFamily}, "Brush Script MT", cursive`;
const FF_MONO = `${cutive.style.fontFamily}, monospace`;

export type CertificateSignature = {
  signer_name: string;
  signer_title: string;
  signature_image_url?: string | null;
  signer_organization?: string | null;
};

export type CertificateData = {
  recipient: {
    first: string;
    last: string;
    township?: string | null;
    county?: string | null;
  };
  course: {
    name: string;
    hours: number | string;
    method: 'in_person' | 'online' | 'hybrid';
    course_date: string;
    course_id: string;
  };
  credential_id: string;
  signatures: CertificateSignature[];
  org_name: string;
  logo_url: string;
  qrDataUrl?: string | null;
  sboaQrDataUrl?: string | null;
  verifyUrl?: string | null;
};

const METHOD_LABEL: Record<CertificateData['course']['method'], string> = {
  in_person: 'In-Person',
  online: 'Online',
  hybrid: 'Hybrid',
};

function formatHours(hours: number | string) {
  const n = typeof hours === 'string' ? parseFloat(hours) : hours;
  if (!Number.isFinite(n)) return '0.0';
  return n.toFixed(1);
}

// Recipient name shrinks just enough so it doesn't wrap past two lines —
// any more and the signature row below gets pushed down off the page.
// Pinyon Script at 86px fits ~27 chars on one line in the 860px content
// width; bands below give 1- or 2-line layouts at most.
function getRecipientNameFontSize(name: string): number {
  const len = name.length;
  if (len <= 22) return 86;
  if (len <= 32) return 74;
  if (len <= 44) return 62;
  return 52;
}

// Course name shrinks as it gets longer so it stays within the safe content
// width. When the recipient name is also long, shrink one extra step since
// the whole layout is tighter overall.
function getCourseNameFontSize(courseName: string, recipientName: string): number {
  const len = courseName.length;
  const nameLong = recipientName.length > 18;
  if (len > 70) return nameLong ? 22 : 24;
  if (len > 55) return nameLong ? 24 : 26;
  if (len > 42) return nameLong ? 26 : 30;
  if (len > 30) return nameLong ? 30 : 32;
  return 34;
}

// When the recipient name is short (one wrapped line), the upper content
// block (presentation line through the pill badges) sits higher than feels
// balanced — there's a lot of empty space between the pills and the
// signatures. Push it down. Long names already fill the vertical space by
// wrapping, so leave them alone.
function getUpperBlockMarginTop(recipientName: string): number {
  return recipientName.length <= 20 ? 52 : 26;
}

function formatDate(iso: string) {
  // Accept YYYY-MM-DD or full ISO; render as e.g. "April 22, 2026". Build the
  // Date in local time when given YYYY-MM-DD so we don't get a one-day shift
  // from UTC parsing.
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  const d = m
    ? new Date(parseInt(m[1], 10), parseInt(m[2], 10) - 1, parseInt(m[3], 10))
    : new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

type Props = {
  data: CertificateData;
  innerRef?: React.Ref<HTMLDivElement>;
};

export function Certificate({ data, innerRef }: Props) {
  const {
    recipient,
    course,
    credential_id,
    signatures,
    org_name,
    logo_url,
    qrDataUrl,
    sboaQrDataUrl,
    verifyUrl,
  } = data;

  // Verify label split into host + path so the line breaks cleanly at the
  // slash on every domain (instead of mid-character break-all wrapping).
  // The QR encodes the full URL with the credential ID — these two lines
  // are just a hint for visitors who can't scan.
  const verifyLabel = (() => {
    const fallbackHost = 'township-tools.vercel.app';
    if (!verifyUrl) return { host: fallbackHost, path: '/certificates/verify' };
    try {
      const u = new URL(verifyUrl);
      return { host: u.host, path: '/certificates/verify' };
    } catch {
      return { host: fallbackHost, path: '/certificates/verify' };
    }
  })();

  const fullName = [recipient.first, recipient.last].filter(Boolean).join(' ').trim();

  const locationLine = (() => {
    const parts: string[] = [];
    if (recipient.township) parts.push(recipient.township);
    if (recipient.county) parts.push(`${recipient.county} County`);
    return parts.length ? parts.join(', ') : null;
  })();

  // Exactly one signer renders on the certificate. Legacy data with two
  // signers stored in the DB is trimmed to the first.
  const effectiveSignatures = (signatures.length
    ? signatures
    : [
        {
          signer_name: 'Indiana Township Association',
          signer_title: 'Executive Director',
          signature_image_url: null,
        },
      ]
  ).slice(0, 1);

  return (
    <div
      ref={innerRef}
      style={{
        position: 'relative',
        width: CERT_WIDTH,
        height: CERT_HEIGHT,
        background: PAPER,
        color: INK,
        fontFamily: FF_BODY,
        overflow: 'hidden',
        boxSizing: 'border-box',
      }}
    >
      {/* Layered professional border */}
      <GuillocheBorder width={CERT_WIDTH} height={CERT_HEIGHT} />

      {/* Corner sprigs at the top corners only. The bottom corners hold the
          ITA logo (left) and QR verify seal (right). */}
      <div style={{ position: 'absolute', top: 64, left: 64 }}>
        <CornerFleuron corner="tl" size={54} />
      </div>
      <div style={{ position: 'absolute', top: 64, right: 64 }}>
        <CornerFleuron corner="tr" size={54} />
      </div>

      {/* Top ribbon banner — title lives inside, no logo overlap. */}
      <RibbonBanner
        totalWidth={CERT_WIDTH}
        subtitle={`Authorized by the ${org_name}`}
        title="Certificate of Completion"
        top={68}
        height={104}
      />

      {/* Main content stack. Starts below the ribbon and ends well inside the
          bottom gold rule so the signature block can't push past the border.
          The spacer at the bottom keeps the signatures pinned to the same Y
          position regardless of how much top padding we add. */}
      <div
        style={{
          position: 'absolute',
          top: 200,
          left: 96,
          right: 96,
          bottom: 130,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          textAlign: 'center',
        }}
      >
        {/* Presentation line stays anchored at the top of the content area.
            CertificateDownloadButton shifts it up in PDF together with the
            upper block below, so the whole "presented to → IC line" group
            lifts as one. */}
        <div
          data-cert-presentation
          style={{
            fontSize: 24,
            fontStyle: 'italic',
            color: NAVY,
            marginTop: getUpperBlockMarginTop(fullName),
          }}
        >
          This certificate is proudly presented to
        </div>

        {/* Wrapped upper block: name → pills. CertificateDownloadButton
            applies a single translateY to this wrapper before capture, so
            the whole block lifts toward the presentation line in the PDF
            without disturbing the signature row below. */}
        <div
          data-cert-upper-block
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            width: '100%',
          }}
        >
          {/* Recipient name (Pinyon Script). Font scales down for long
              names so the block stays at most two wrapped lines and the
              signature row below doesn't get pushed past the bottom border. */}
          <div
            style={{
              fontFamily: FF_SCRIPT,
              fontSize: getRecipientNameFontSize(fullName),
              color: NAVY,
              lineHeight: 1,
              marginTop: 16,
              padding: '0 24px',
              maxWidth: '100%',
              textAlign: 'center',
              wordBreak: 'break-word',
            }}
          >
            {fullName || ' '}
          </div>

          {/* Gold-diamond underline. CertificateDownloadButton nudges this
              wrapper down in PDF since html2canvas renders it slightly
              higher than the preview does. */}
          <div data-cert-name-underline style={{ marginTop: 20 }}>
            <NameUnderline width={540} />
          </div>

          {/* Completion clause. */}
          <div
            style={{
              fontSize: 22,
              fontStyle: 'italic',
              color: NAVY,
              marginTop: 18,
              maxWidth: 820,
            }}
          >
            {locationLine
              ? <>of {locationLine}, for the successful completion of</>
              : <>for the successful completion of</>}
          </div>

          {/* Course name — rendered in deep gold to stand out from the
              navy body text without breaking the navy-and-gold palette. */}
          <div
            data-cert-course-name
            style={{
              fontFamily: FF_BODY,
              fontSize: getCourseNameFontSize(course.name, fullName),
              fontWeight: 700,
              color: GOLD,
              marginTop: 10,
              maxWidth: 880,
              lineHeight: 1.18,
            }}
          >
            {course.name}
          </div>

          {/* Pill badges. */}
          <div
            style={{
              display: 'flex',
              gap: 16,
              marginTop: 22,
              flexWrap: 'wrap',
              justifyContent: 'center',
            }}
          >
            <Pill>Completed&nbsp;·&nbsp;{formatDate(course.course_date)}</Pill>
            <Pill>
              {formatHours(course.hours)} Hours&nbsp;·&nbsp;{METHOD_LABEL[course.method]}
            </Pill>
          </div>

          {/* IC 36-6-4-20 certification statement. Small italic line sits
              directly under the pills as part of the upper block, so the
              upper-block DOM-prep translateY shifts it together with the
              name/course/pills group. Width caps at ~580px so the text
              wraps to roughly the combined width of the two pills above
              rather than stretching across the full content area. */}
          <div
            style={{
              fontFamily: FF_BODY,
              fontStyle: 'italic',
              fontSize: 13,
              color: NAVY,
              opacity: 0.85,
              marginTop: 8,
              maxWidth: 580,
              lineHeight: 1.4,
              textAlign: 'center',
            }}
          >
            The Indiana Township Association certifies that this training course
            is designed to meet applicable educational standards outlined in
            Indiana Code IC&nbsp;36-6-4-20.
          </div>
        </div>

      </div>

      {/* Signature block, anchored to the bottom-right of the cert. Lives
          outside the content stack so it sits at the same Y baseline as
          the SBOA block on the left, with no overlap of the disclosure
          text and a clear gap to the verify seal further right. */}
      <div
        data-cert-signature-row
        style={{
          position: 'absolute',
          right: 230,
          bottom: 60,
          width: 320,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        {effectiveSignatures.length > 0 && (
          <SignatureBlock signer={effectiveSignatures[0]} />
        )}
      </div>

      {/* Course ID (left) and Credential ID (right) — placed just under the
          ribbon as a reference header. Cormorant Garamond for readability. */}
      <div
        style={{
          position: 'absolute',
          left: 100,
          right: 100,
          top: 184,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontFamily: FF_BODY,
          fontSize: 15,
          fontWeight: 500,
          letterSpacing: '0.02em',
          color: NAVY,
          zIndex: 1,
        }}
      >
        <span>Course ID · {course.course_id}</span>
        <span>Credential ID · {credential_id}</span>
      </div>

      {/* ITA logo medallion, anchored in the bottom-LEFT corner. Large
          (130px) so it reads as the issuing authority's seal. */}
      <div
        data-cert-logo-block
        style={{
          position: 'absolute',
          left: 66,
          bottom: 60,
          pointerEvents: 'none',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 4,
          width: 130,
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={logo_url}
          alt=""
          crossOrigin="anonymous"
          loading="eager"
          decoding="sync"
          style={{
            width: 130,
            height: 130,
            objectFit: 'contain',
          }}
        />
        <div
          style={{
            fontFamily: FF_BODY,
            fontStyle: 'italic',
            fontSize: 9,
            color: NAVY,
            opacity: 0.8,
            textAlign: 'center',
            letterSpacing: '0.02em',
          }}
        >
          More trainings at ita-in.org
        </div>
      </div>

      {/* QR verify seal, anchored in the bottom-right corner with a small
          "Verify at:" caption above and the verify URL below. */}
      <div
        data-cert-verify-block
        style={{
          position: 'absolute',
          right: 80,
          bottom: 60,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 2,
          maxWidth: 130,
        }}
      >
        <div
          data-cert-verify-label
          style={{
            fontFamily: FF_BODY,
            fontSize: 9,
            fontWeight: 600,
            color: NAVY,
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
          }}
        >
          Verify at:
        </div>
        <VerifySeal size={84} qrDataUrl={qrDataUrl} />
        <div
          style={{
            fontFamily: FF_BODY,
            fontSize: 8,
            color: NAVY,
            opacity: 0.85,
            textAlign: 'center',
            lineHeight: 1.2,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
          }}
        >
          <div>{verifyLabel.host}</div>
          <div>{verifyLabel.path}</div>
        </div>
      </div>

      {/* SBOA disclosure + QR at the bottom-left, right next to the ITA
          logo. Vertical layout: disclosure text on top, QR in the middle,
          upload URL beneath. Sits at the same bottom: 60 baseline as the
          signature on the right side, with a clear horizontal gap so
          nothing overlaps. */}
      <div
        data-cert-sboa-block
        style={{
          position: 'absolute',
          left: 210,
          bottom: 60,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 4,
          width: 300,
          textAlign: 'center',
        }}
      >
        <div
          data-cert-sboa-text
          style={{
            fontFamily: FF_BODY,
            fontSize: 8,
            color: NAVY,
            lineHeight: 1.3,
            opacity: 0.9,
          }}
        >
          Per IC&nbsp;36-6-4-20, attendees are responsible for submitting proof of
          training completion via the Indiana SBOA Election Official Certification
          of Training Courses Upload Tool.
        </div>
        {sboaQrDataUrl && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={sboaQrDataUrl}
            alt="SBOA upload tool QR"
            crossOrigin="anonymous"
            style={{ width: 64, height: 64, display: 'block' }}
          />
        )}
        <div
          style={{
            fontFamily: FF_BODY,
            fontSize: 8,
            color: NAVY,
            opacity: 0.85,
            letterSpacing: '0.02em',
          }}
        >
          gateway.ifionline.org/sboa_EOTC
        </div>
      </div>

    </div>
  );
}

function NameUnderline({ width = 540 }: { width?: number }) {
  return (
    <svg
      width={width}
      height={14}
      viewBox={`0 0 ${width} 14`}
      style={{ display: 'block' }}
      aria-hidden
    >
      <line
        x1={6}
        y1={7}
        x2={width / 2 - 14}
        y2={7}
        stroke={NAVY}
        strokeWidth={1.2}
      />
      <line
        x1={width / 2 + 14}
        y1={7}
        x2={width - 6}
        y2={7}
        stroke={NAVY}
        strokeWidth={1.2}
      />
      <path
        d={`M ${width / 2 - 9} 7 L ${width / 2} 1 L ${width / 2 + 9} 7 L ${width / 2} 13 Z`}
        fill={GOLD}
      />
    </svg>
  );
}

function Pill({ children }: { children: React.ReactNode }) {
  // Flex-centered text. CertificateDownloadButton applies a small
  // padding-bottom nudge to every [data-cert-pill] right before capture to
  // compensate for the known html2canvas baseline drift (same trick the
  // Report Builder uses on its StatBoxes).
  return (
    <div
      data-cert-pill
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: NAVY,
        color: '#FFFFFF',
        borderRadius: 999,
        padding: '0 28px',
        height: 50,
        fontSize: 19,
        fontWeight: 600,
        fontFamily: FF_BODY,
        letterSpacing: '0.02em',
        whiteSpace: 'nowrap',
        lineHeight: 1,
      }}
    >
      {children}
    </div>
  );
}

function SignatureBlock({ signer }: { signer: CertificateSignature }) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        minWidth: 280,
      }}
    >
      {/* <img> bottom-aligned inside a fixed-height flex box. html2canvas
          renders <img> reliably (bg-image was silently failing for some
          source PNGs); the wrapper's flex-end alignment keeps the bottom
          of the image flush against the rule below regardless of the
          image's natural height. */}
      <div
        style={{
          height: 110,
          width: 320,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'flex-end',
        }}
      >
        {signer.signature_image_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={signer.signature_image_url}
            alt=""
            crossOrigin="anonymous"
            loading="eager"
            decoding="sync"
            style={{
              maxWidth: 320,
              maxHeight: 110,
              display: 'block',
            }}
          />
        ) : (
          <SignaturePlaceholder width={280} height={104} />
        )}
      </div>
      <div
        style={{
          width: 280,
          height: 1.5,
          background: NAVY,
          marginTop: 0,
        }}
      />
      <div
        style={{
          fontFamily: FF_BODY,
          fontSize: 22,
          fontWeight: 600,
          color: NAVY,
          marginTop: 4,
          lineHeight: 1,
        }}
      >
        {signer.signer_name}
      </div>
      <div
        style={{
          fontFamily: FF_BODY,
          fontSize: 15,
          fontWeight: 700,
          color: NAVY,
          marginTop: 6,
          lineHeight: 1.2,
        }}
      >
        {signer.signer_title}
      </div>
      {signer.signer_organization && (
        <div
          style={{
            fontFamily: FF_BODY,
            fontSize: 13,
            fontStyle: 'italic',
            color: NAVY,
            marginTop: 6,
            lineHeight: 1.2,
            opacity: 0.85,
          }}
        >
          {signer.signer_organization}
        </div>
      )}
    </div>
  );
}
